
GET  http://localhost:3000/users HTTP/1.1
Accept: application/json

###

GET  http://localhost:3000/users/unique HTTP/1.1
Accept: application/json

{ "email": "yadir@mum.com" }

###

POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{"username": "yosief", "email": "yosief@mum.com", "password": "yosief" }
//{"username": "yadir", "email": "yadir@mum.com", "password": "yadir" }

###

POST http://localhost:3000/users/signin HTTP/1.1
Content-Type: application/json

{"username": "yosief", "password": "yosief" }

###

PATCH http://localhost:3000/users/add-friend HTTP/1.1
Content-Type: application/json

{ "me": "yosief", "friend": "alvaro" }

###

GET  http://localhost:3000/users/yosief HTTP/1.1
Accept: application/json

