
GET  http://localhost:3000/users HTTP/1.1
Accept: application/json

###

POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{"username": "yosief", "email": "yosief@mum.com", "password": "yosief" }
//{"username": "yadir", "email": "yadir@mum.com", "password": "yadir" }

###

POST http://localhost:3000/users/signin HTTP/1.1
Content-Type: application/json

{"username": "yosief", "password": "yosief" }

###

GET  http://localhost:3000/users/yadir HTTP/1.1
Accept: application/json

